config/routes.rb
Rails.application.routes.draw do
  root to: "sentences#index"
  resources :sentences
  resources :entities
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entity.rb
# == Schema Information
#
# Table name: entities
#
#  id         :bigint           not null, primary key
#  text       :string
#  type       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Entity < ApplicationRecord
  # override inheritance column to avoid clashes with type column
  self.inheritance_column = '_'
  has_many :sentences_entities, dependent: :destroy
  has_many :sentences, through: :sentences_entities
  validates :text, :type, presence: true
  before_save :strip_and_upcase_type

  private

  def strip_and_upcase_type
    self.type = type.strip.upcase
  end
end

app/models/sentence.rb
# == Schema Information
#
# Table name: sentences
#
#  id         :bigint           not null, primary key
#  text       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Sentence < ApplicationRecord
  has_many :sentences_entities, dependent: :destroy
  has_many :entities, through: :sentences_entities, inverse_of: :sentences
  accepts_nested_attributes_for :entities, reject_if: :all_blank, allow_destroy: true
end

app/models/sentences_entity.rb
# == Schema Information
#
# Table name: sentences_entities
#
#  id          :bigint           not null, primary key
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  entity_id   :bigint
#  sentence_id :bigint
#
# Indexes
#
#  index_sentences_entities_on_entity_id    (entity_id)
#  index_sentences_entities_on_sentence_id  (sentence_id)
#
class SentencesEntity < ApplicationRecord
  belongs_to :sentence
  belongs_to :entity
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/entities_controller.rb
class EntitiesController < ApplicationController
  before_action :set_entity, only: %i[ show edit update destroy ]

  # GET /entities or /entities.json
  def index
    @entities = Entity.all
  end

  # GET /entities/1 or /entities/1.json
  def show
  end

  # GET /entities/new
  def new
    @entity = Entity.new
  end

  # GET /entities/1/edit
  def edit
  end

  # POST /entities or /entities.json
  def create
    @entity = Entity.new(entity_params)

    respond_to do |format|
      if @entity.save
        format.html { redirect_to entity_url(@entity), notice: "Entity was successfully created." }
        format.json { render :show, status: :created, location: @entity }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @entity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entities/1 or /entities/1.json
  def update
    respond_to do |format|
      if @entity.update(entity_params)
        format.html { redirect_to entity_url(@entity), notice: "Entity was successfully updated." }
        format.json { render :show, status: :ok, location: @entity }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @entity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entities/1 or /entities/1.json
  def destroy
    @entity.destroy

    respond_to do |format|
      format.html { redirect_to entities_url, notice: "Entity was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entity
      @entity = Entity.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def entity_params
      params.require(:entity).permit(:text, :type)
    end
end

app/controllers/sentences_controller.rb
class SentencesController < ApplicationController
  before_action :set_sentence, only: %i[ show edit update destroy ]

  # GET /sentences or /sentences.json
  def index
    @sentences = Sentence.all.includes(:entities)
  end

  # GET /sentences/1 or /sentences/1.json
  def show
  end

  # GET /sentences/new
  def new
    @sentence = Sentence.new
  end

  # GET /sentences/1/edit
  def edit
  end

  # POST /sentences or /sentences.json
  def create
    @sentence = Sentence.new(sentence_params)

    respond_to do |format|
      if @sentence.save
        format.html { redirect_to sentence_url(@sentence), notice: "Sentence was successfully created." }
        format.json { render :show, status: :created, location: @sentence }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @sentence.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sentences/1 or /sentences/1.json
  def update
    respond_to do |format|
      if @sentence.update(sentence_params)
        format.html { redirect_to sentence_url(@sentence), notice: "Sentence was successfully updated." }
        format.json { render :show, status: :ok, location: @sentence }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @sentence.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sentences/1 or /sentences/1.json
  def destroy
    @sentence.destroy

    respond_to do |format|
      format.html { redirect_to sentences_url, notice: "Sentence was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sentence
      @sentence = Sentence.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def sentence_params
      # Allow entity text in both string and array format
      permitted = params.require(:sentence).permit(:text, entities_attributes: [:id, :text, :type, :_destroy, {text: []}])
      permitted[:entities_attributes]&.each do |_, entity_data|
        entity_data[:text] = entity_data[:text]&.split&.join(" ")&.strip
      end
      permitted
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def show_sentence_with_entities(sentence)
    text = sentence.text
    # Try to avoid overriding spans as much as possible by sorting in descending length
    sentence.entities.to_a.sort{|el| el.text.length}.each do |entity|
      style = styling_data(entity.type)
      text.gsub!(entity.text,
        "<span class='element' style='background-color: #{style[:bg_color]}; color: #{style[:text_color]}'>
          #{entity.text} <sup>#{entity.type}</sup>
        </span>"
      )
    end
    text.html_safe
  end

  def styling_data(type)
    # Generate styling data (bg-color and text color) based on type characters on the fly
    # Group styling based on entity type in order to provide a more uniform UX
    # Use YIQ similar to Bootstrap's color-yiq https://en.wikipedia.org/wiki/YIQ
    @styling_data ||= {}
    return @styling_data[type] || add_styling_data(type)
  end

  private

  def add_styling_data(type)
    # Use same algorithm so same color scheme is always generated
    sum = type.each_char.map(&:ord).sum
    r = (sum*3) % 255
    g = (sum*4) % 255
    b = (sum*5) % 255
    hsp = Math.sqrt(0.299 * (r * r) + 0.587 * (g * g) + 0.114 * (b * b))
    text_color = hsp > 127.5 ? "black" : "white"
    @styling_data[type] = {
      bg_color: "rgb(#{r},#{g},#{b})",
      text_color: text_color
    }
  end
end

app/helpers/entities_helper.rb
module EntitiesHelper
end

app/helpers/sentences_helper.rb
module SentencesHelper
end

app/views/entities/_form.html.erb
<%= form_with(model: entity) do |form| %>
  <% if entity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(entity.errors.count, "error") %> prohibited this entity from being saved:</h2>

      <ul>
        <% entity.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :text %>
    <%= form.text_field :text %>
  </div>

  <div class="field">
    <%= form.label :type %>
    <%= form.text_field :type %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/entities/edit.html.erb
<h1>Editing Entity</h1>

<%= render 'form', entity: @entity %>

<%= link_to 'Show', @entity %> |
<%= link_to 'Back', entities_path %>

app/views/entities/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Entities</h1>

<table>
  <tbody>
    <% @entities.each do |entity| %>
      <% style = styling_data(entity.type) %>
      <tr>
        <td><%= entity.text %></td>
        <td><span class='element' style='background-color: <%=style[:bg_color]%>; color: <%=style[:text_color]%>'><%= entity.type %></span></td>
        <td><%= link_to 'Show', entity %></td>
        <td><%= link_to 'Edit', edit_entity_path(entity) %></td>
        <td><%= link_to 'Destroy', entity, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Entity', new_entity_path %>

app/views/entities/new.html.erb
<h1>New Entity</h1>

<%= render 'form', entity: @entity %>

<%= link_to 'Back', entities_path %>

app/views/entities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Text:</strong>
  <%= @entity.text %>
</p>

<p>
  <strong>Type:</strong>
  <%= @entity.type %>
</p>

<%= link_to 'Edit', edit_entity_path(@entity) %> |
<%= link_to 'Back', entities_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sentences Entities</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.1/jquery.min.js" integrity="sha512-aVKKRRi/Q/YV+4mjoKBsE4x3H+BkegoM/em46NNlCqNTmUYADjBbeNefNxYV7giUp0VxICtqdrbqU7iVaeZNXA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
  </head>

  <body>
    <header>
      <h4>Sentences Entities</h4>
      <%= link_to "Sentences", sentences_path %> | <%= link_to "Entities", entities_path %>
    </header>
    <hr>
    <%= yield %>
  </body>
</html>

app/views/sentences/_entity_fields.html.erb
<div class="nested-fields">
  <div class="field">
    <%= f.label :text %>
    <small>Multiple selections will automatically be separated by a single space.</small>
    <br>
    <%= f.select :text, 
        options_for_select(f.object&.text&.split(' ').to_a, f.object&.text&.split(' ').to_a), {},
        { class: "entity-fields-multiple", multiple: "multiple", required: true } %>
  </div>
  <div class="field">
    <%= f.label :type %>
    <br>
    <%= f.text_field :type %>
  </div>
  <%= link_to_remove_association "Remove entity", f %>
</div>
<br>

app/views/sentences/_form.html.erb
<%= form_with(model: sentence) do |form| %>
  <% if sentence.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sentence.errors.count, "error") %> prohibited this sentence from being saved:</h2>

      <ul>
        <% sentence.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :text %>
    <%= form.text_area :text, cols: 80 %>
  </div>

  <hr>

  <div id='entities'>
    <h5>Entities</h5>
    <hr>
    <%= form.fields_for :entities do |entity| %>
      <%= render 'entity_fields', :f => entity %>
    <% end %>
    <div class='links'>
      <%= link_to_add_association 'Add entity', form, :entities %>
    </div>
  </div>

  <hr>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<%= javascript_pack_tag 'entity_fields' %>

app/views/sentences/edit.html.erb
<h1>Editing Sentence</h1>

<%= render 'form', sentence: @sentence %>

<%= link_to 'Show', @sentence %> |
<%= link_to 'Back', sentences_path %>

app/views/sentences/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sentences</h1>

<table>
  <tbody>
    <% @sentences.each do |sentence| %>
      <tr>
        <td><h3><%= show_sentence_with_entities(sentence) %></h3></td>
        <td><%= link_to 'Show', sentence %></td>
        <td><%= link_to 'Edit', edit_sentence_path(sentence) %></td>
        <td><%= link_to 'Destroy', sentence, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sentence', new_sentence_path %>

app/views/sentences/new.html.erb
<h1>New Sentence</h1>

<%= render 'form', sentence: @sentence %>

<%= link_to 'Back', sentences_path %>

app/views/sentences/show.html.erb
<p id="notice"><%= notice %></p>

<h3>
  <%= show_sentence_with_entities(@sentence) %>
</h3>

<h5>Entities:</h5>
<% @sentence.entities.each do |entity| %>
  <p>Text: <%= entity.text %>. Type: <%= entity.type %></p>
<% end %>
<%= link_to 'Edit', edit_sentence_path(@sentence) %> |
<%= link_to 'Back', sentences_path %>